# Generated by Django 5.0.3 on 2024-03-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=100)),
                ('atividade_principal', models.CharField(max_length=100)),
                ('numero_endereco', models.CharField(max_length=150)),
                ('cep', models.IntegerField()),
                ('municipio', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=40)),
            ],
        ),
    ]
